api/main_service/MainService/Controllers/SongsController.cs, api/main_service/MainService/Dtos/FilterDto.cs, api/main_service/MainService/Dtos/SongDto.cs, api/main_service/MainService/Logic/SongLogic.cs
Ticket:
https://app.clickup.com/t/3gw3dqa
https://app.clickup.com/t/3gw3e1v
Changes:
- Add get song by id api
- Add get songs by genres api
=> feat: get song(s) by id, genres api

api/main_service/MainService/Controllers/SongsController.cs, api/main_service/MainService/Dtos/FilterDto.cs, api/main_service/MainService/Dtos/SongDto.cs, api/main_service/MainService/Logic/SongLogic.cs, api/main_service/MainService/Models/Song.cs, client/src/api/song-api.ts, client/src/components/Admin/Create/LyricsInput.tsx, client/src/components/Home/Feature.tsx, client/src/components/Home/Result.tsx, client/src/components/SkeletonLoading/TextLoading.tsx, client/src/components/SkeletonLoading/VideoLoading.tsx, client/src/components/Song/SongDetail.tsx, client/src/pages/Song.tsx, client/src/pages/admin/Song/Create.tsx, client/src/store/index.ts, client/src/store/slices/recommendSlice.ts, client/src/store/slices/songRecommendSlice.ts, client/src/store/slices/songSlice.ts, client/src/types/song.d.ts
Ticket:
https://app.clickup.com/t/3gw3dqt
Changes:
- Remove existed song when recommend related song
- Add song detail page, components
- Update Result and fix some typo in Song model
=> feat: song detail page

api/main_service/MainService/Controllers/SongsController.cs, api/main_service/MainService/Data/Repository.cs, api/main_service/MainService/Dtos/SongDto.cs, api/main_service/MainService/Dtos/UrlDto.cs, api/main_service/MainService/Logic/SongLogic.cs, api/main_service/MainService/Profiles/SongProfile.cs, api/main_service/MainService/Profiles/UrlProfile.cs, api/main_service/MainService/Services/S3Service.cs, api/main_service/MainService/Utils/MongoIdUtils.cs, api/main_service/MainService/Utils/ResponseMessage.cs, client/src/api/song-api.ts, client/src/components/Admin/Create/InfoInput.tsx, client/src/components/Admin/Create/ThumbnailInput.tsx, client/src/components/shared/Dropdown.tsx, client/src/components/shared/FileDropzone.tsx, client/src/components/shared/ImageDropzone.tsx, client/src/components/shared/Nav.tsx, client/src/components/shared/SelectAsync.tsx, client/src/components/shared/Table.tsx, client/src/pages/admin/Dashboard.tsx, client/src/pages/admin/Song/Create.tsx, client/src/pages/admin/Song/Edit.tsx, client/src/pages/admin/Song/View.tsx, client/src/routes/admin-routes.tsx, client/src/store/slices/songSlice.ts, client/src/types/dropdown.d.ts, client/src/types/song.d.ts
Ticket:
https://app.clickup.com/t/3k6htvt
https://app.clickup.com/t/3k6htz5
Change:
- Add song edit api
- Change update in api repository
- Add song edit ui
- Add navigate to admin page
=> feat: edit song information

api/main_service/MainService/Controllers/GenresController.cs, client/src/api/genre-api.ts, client/src/components/Modal/Modal.tsx, client/src/pages/admin/Genre.tsx, client/src/routes/admin-routes.tsx, client/src/store/index.ts, client/src/store/slices/genreSlice.ts
Ticket:
https://app.clickup.com/t/3kcan2a
Changes:
- Add genre manage page
- Add create genre
- Add delete genre
=> feat: genre manage page

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Data/Repository.cs, api/main_service/MainService/Dtos/PostDto.cs, api/main_service/MainService/Logic/AccountLogic.cs, api/main_service/MainService/Models/Account.cs, api/main_service/MainService/Models/Comment.cs, api/main_service/MainService/Models/Post.cs, api/main_service/MainService/Models/Report.cs, api/main_service/MainService/Profiles/PostProfile.cs
Changes:
- Add new method to repository
- Change _id of account from ObjectId to string(Uid)
- Add get post by id api
=> fix: _id in Account collection, count document for full-text search in repository

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Dtos/PostDto.cs, api/main_service/MainService/Models/Post.cs, api/main_service/MainService/Profiles/PostProfile.cs, api/main_service/MainService/Utils/HelperClass.cs, api/main_service/MainService/Utils/ResponseMessage.cs
=> feat: api create post

api/main_service/MainService/Controllers/ReportsController.cs, api/main_service/MainService/Dtos/ReportDto.cs, client/src/api/report-api.ts, client/src/components/Admin/Create/StepForm.tsx, client/src/components/Discover/HumCard.tsx, client/src/components/Modal/Modal.tsx, client/src/components/Modal/ModalForm.tsx, client/src/components/Report/PostReport.tsx, client/src/components/Report/ReportForm.tsx, client/src/pages/admin/Song/Create.tsx, client/src/pages/admin/Song/Edit.tsx, client/src/store/index.ts, client/src/store/slices/reportSlice.ts, client/src/types/report.d.ts, client/src/utils/constants.ts, client/src/utils/useOutsideClick.ts
Ticket:
https://app.clickup.com/t/3kcbbhm
Changes:
- Move Post report logic to new component
- Add ModalForm component
- Move outsideClick to a hook in utils
=> feat: create report ui

client/src/components/Modal/Modal.tsx, client/src/pages/admin/Song/View.tsx
=> fix: modal delete song ui

api/main_service/MainService/Controllers/ReportsController.cs, api/main_service/MainService/Dtos/FilterDto.cs, api/main_service/MainService/Logic/ReportLogic.cs, api/main_service/MainService/Models/Report.cs, api/main_service/MainService/Utils/Constant.cs
Ticket:
https://app.clickup.com/t/3megpy4
Changes:
- Add list reports api with filter
- Add report status when confirm
=> feat: list reports api

client/src/components/Discover/DiscoverHeader.tsx, client/src/components/Discover/PostCard.tsx, client/src/components/Discover/PostCreate.tsx, client/src/components/Discover/RightComponent.tsx, client/src/components/Discover/SearchBox.tsx, client/src/components/Posts/createPostInfiniteScrollLayout.tsx, client/src/pages/Post.tsx, client/src/pages/Search.tsx, client/src/theme/Discover.css
=> feat: fe post search

api/main_service/MainService/Controllers/ReportsController.cs, api/main_service/MainService/Dtos/ReportDto.cs, api/main_service/MainService/Logic/CommentLogic.cs, api/main_service/MainService/Logic/PostLogic.cs, api/main_service/MainService/Logic/ReportLogic.cs, client/src/pages/admin/Report/View.tsx, client/src/store/slices/hashtagSlice.ts, client/src/types/report.d.ts
Ticket:
https://app.clickup.com/t/3megpyg
Changes:
- Add new apis confirm report and get report detail
- Update display information in view report page
- Fix genre manage page bug with hashtag slice
=> feat: confirm report api, fix: hashtag slice, view report pages

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Utils/Constant.cs, api/main_service/MainService/Utils/ResponseMessage.cs
fix: view post show deleted post
=> fix: view post show deleted post

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Dtos/FilterDto.cs, api/main_service/MainService/Logic/PostLogic.cs, client/src/components/Discover/PostCreate.tsx, client/src/components/InfiniteScroll/createPostInfiniteScrollLayout.tsx, client/src/components/Profile/ProfileCard.tsx
=> feat: api view user post

client/src/api/post-api.ts, client/src/components/InfiniteScroll/createPostInfiniteScrollLayout.tsx, client/src/pages/Discover.tsx, client/src/pages/user/Profile.tsx, client/src/store/slices/postSlice.ts, client/src/types/components.d.ts, client/src/types/post.d.ts
=> feat: fe view user post

api/main_service/MainService/Program.cs, client/package.json, client/src/api/comment-api.ts, client/src/components/Comment/CommentCard.tsx, client/src/components/Comment/CommentCreate.tsx, client/src/components/Comment/CommentInput.tsx, client/src/components/Comment/CommentSection.tsx, client/src/components/Comment/MediaDisplay.tsx, client/src/components/shared/FileDropzone.tsx, client/src/store/slices/commentSlice.ts, client/src/types/comment.d.ts, client/src/utils/constants.ts
Ticket:
https://app.clickup.com/t/3qnnvez
Changes:
- Add new comment create component
- Add new MediaDisplay for auto selecting media displayer
=> feat: create comment ui

api/main_service/MainService/Controllers/NotifysController.cs, api/main_service/MainService/Data/NotifyRepo.cs, api/main_service/MainService/Dtos/EventDto.cs, api/main_service/MainService/Dtos/FilterDto.cs, api/main_service/MainService/Events/EventProcessor.cs, api/main_service/MainService/Hubs/NotifyHub.cs, api/main_service/MainService/Logic/ReportLogic.cs, api/main_service/MainService/Models/Notify.cs, api/main_service/MainService/Profiles/NotifyProfile.cs, api/main_service/MainService/Program.cs, api/main_service/MainService/Services/MessageQueuePublisher.cs, api/main_service/MainService/Utils/Constant.cs, api/main_service/MainService/Utils/ResponseMessage.cs
=> feat: be notification

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Utils/ResponseMessage.cs, client/src/components/Discover/PostCreate.tsx, client/src/components/InfiniteScroll/InfiniteScroll.css, client/src/theme/Discover.css
fix bug of api, ui create post
=> fix: create post

api/main_service/MainService/Controllers/SongsController.cs
fix: delete song with not found id
=> fix: delete song with not found id

api/main_service/MainService/Logic/PostLogic.cs, api/main_service/MainService/Logic/SongLogic.cs
=> fix: view post and view song

client/cypress.config.ts, client/cypress/e2e/register.cy.ts, client/src/components/Auth/SignUpForm.tsx, client/src/components/Toast/Toast.tsx, client/src/components/shared/Input.tsx, client/src/components/shared/Nav.tsx, client/src/pages/auth/VerifyEmail.tsx
Ticket:
https://app.clickup.com/t/3tmfa4j
Change:
- Add new test suit for register
- Change config url from staging to dev
=> test: register feature

api/main_service/MainService/Filters/ValidValues.cs, client/cypress/e2e/view_users.cy.ts, client/cypress/fixtures/admin.json, client/src/components/Auth/LoginForm.tsx, client/src/components/Nav.Left/LeftNav.Item.tsx, client/src/components/shared/Dropdown.tsx, client/src/components/shared/Nav.tsx, client/src/components/shared/SearchFilter.tsx, client/src/components/shared/Table.tsx, client/src/pages/admin/Report/View.tsx, client/src/routes/moderator-routes.tsx, client/src/utils/constants.ts
Ticket:
https://app.clickup.com/t/3tmfaxz
Change:
- Add new test case for view users
=> test: view users

client/cypress/e2e/view_profile.cy.ts, client/src/components/Post/PostCard.tsx, client/src/components/shared/Nav.tsx
=> test: view profile

client/cypress/e2e/vote.cy.ts, client/src/components/Comment/CommentVote.tsx, client/src/components/Post/PostCard.tsx, client/src/components/Post/Vote.tsx
=> test: post and comment vote

client/cypress/e2e/view_songs.cy.ts
Ticket:
https://app.clickup.com/t/3tmfb5u
Changes:
- Add new test case for view songs feature
=> test: view songs

client/cypress/e2e/edit_profile.cy.ts, client/src/components/Profile/ProfileCard.tsx, client/src/components/ProfileEdit/AvatarDropzone.tsx, client/src/components/ProfileEdit/ProfileEdit.tsx, client/src/components/ProfileEdit/ProfileEditButton.tsx
Ticket:
https://app.clickup.com/t/3tmfb04
Change:
- Add new test for edit profile
- Change some component for adding data-cy
=> test: edit profile

client/cypress/e2e/grant_role.cy.ts, client/src/components/Admin/User/UserManageButtonLayout.tsx, client/src/components/shared/Table.tsx
Ticket:
https://app.clickup.com/t/3tmfb5b
Changes:
- Add test cases for granting role feature
=> test: grant role

client/cypress/e2e/create_song.cy.ts, client/src/components/Admin/Create/InfoInput.tsx, client/src/components/Admin/Create/LyricsInput.tsx, client/src/components/Admin/Create/ThumbnailInput.tsx, client/src/components/Admin/Create/TrackInput.tsx, client/src/components/Admin/Create/UrlInput.tsx, client/src/components/Admin/View/ViewHeader.tsx, client/src/components/shared/FileDropzone.tsx, client/src/components/shared/ImageDropzone.tsx
=> test: create song

client/cypress/e2e/ban_users.cy.ts
=> test: ban users

client/cypress/e2e/comment.cy.ts, client/src/components/Comment/CommentCard.tsx, client/src/components/Comment/CommentDeleteButton.tsx, client/src/components/Modal/Modal.tsx
=> test: comment

api/main_service/MainService/Controllers/CommentsController.cs, api/main_service/MainService/Dtos/CommentDto.cs, api/main_service/MainService/Logic/CommentLogic.cs, api/main_service/MainService/Utils/ResponseMessage.cs, client/src/components/Comment/CommentCreate.tsx, client/src/store/slices/commentSlice.ts
Changes:
- Not allow user to input space
- Allow nullable for content or media
- Fix infinite loading when fail to create comment
- Change response message for creating comment
=> fix: create comment bugs

client/src/components/Discover/PostCreate.tsx, client/src/components/shared/TabsNav.tsx
=> fix: tab navigation

api/main_service/MainService/Controllers/PostsController.cs, api/main_service/MainService/Logic/PostLogic.cs
=> fix: user post

client/src/components/Discover/PostCreate.tsx, client/src/components/Notification/NotificationCard.tsx
fix: create post add delete file button
=> fix: create post add delete file button

client/src/components/shared/SelectRow.tsx
=> fix: select row style
